function timestamp() {
  // sometime in the last 30 days
  const stampy =
    Date.now() - Math.floor(Math.random() * 1000 * 60 * 60 * 24 * 30);
  return new Date(stampy).toISOString();
}
// TODO: ZMIENIC publicID
export const exercises = [
  {
    name: 'Conditioning',
    description: 'start z 2 point -> niedźwiedzie (zejście prosto z pozycji OL) -> sprint ->przeskoki przez płotki (zmieniać strony)',
    position: 'OL',
    photo: {
      id: '5dfbed262849d7961377c2c0',
      filename: 'conditioningOL.png',
      originalFilename: 'conditioningOL.png',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'coach-zone-keystone/5dfbed262849d7961377c2c0',
        width: 750,
        height: 457,
        format: 'png',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 27871,
        type: 'upload',
        etag: 'e1fdf84d5126b6ca2e1c8ef9532be5a5',
        placeholder: false,
        url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843094/coachzone/conditioningOL_xfpf7h.png',
        secure_url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843094/coachzone/conditioningOL_xfpf7h.png',
        original_filename: 'file',
      },
    },
    // createdBy: null,
    // updatedBy: null,
    // updatedAt_utc: '2020-12-19T21:35:35.739Z',
    // updatedAt_offset: '+00:00',
    // createdAt_utc: '2020-12-19T21:35:35.739Z',
    // createdAt_offset: '+00:00',
  },
  {
    name: 'Conditioning',
    description: 'release -> sprint -> quickstepy wokół conów x3 + łapanie piłki tenisowej -> cut na hexach (zmieniać strony) piłka tenisowa',
    position: 'RB',
    photo: {
      id: '5dfbed262849d7961377c2c0',
      filename: 'conditioningWRpng',
      originalFilename: 'conditioningWR.png',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'coach-zone-keystone/5e2a13f0689b2835ae71d1a5',
        width: 750,
        height: 457,
        format: 'png',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 27871,
        type: 'upload',
        etag: 'e1fdf84d5126b6ca2e1c8ef9532be5a5',
        placeholder: false,
        url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843260/coachzone/conditioningWR_htria7.png',
        secure_url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843260/coachzone/conditioningWR_htria7.png',
        original_filename: 'file',
      },
    },
    // createdBy: null,
    // updatedBy: null,
    // updatedAt_utc: '2020-12-19T21:35:35.739Z',
    // updatedAt_offset: '+00:00',
    // createdAt_utc: '2020-12-19T21:35:35.739Z',
    // createdAt_offset: '+00:00',
  },
  {
    name: 'IZ vs slant DL + LB',
    description: 'dwóch OL ustawia się w linii. Naprzeciwko jednego (heads up), po stronie biegu ustawia się DL. Za DL staje LB. Na start DL wchodzi w jedną z dziur (umawia się z LB w którą), a LB wbiega w drugą. OL blokują swoje dziury. Za OL rusza RB i wbiega w dziurę nie wybraną przez DL',
    position: 'OL',
    photo: {
      id: '5dfbed262849d7961377c2c0',
      filename: 'iz.png',
      originalFilename: 'iz.png',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'coach-zone-keystone/5e2a13ff689b2835ae71d1a7',
        width: 750,
        height: 457,
        format: 'png',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 27871,
        type: 'upload',
        etag: 'e1fdf84d5126b6ca2e1c8ef9532be5a5',
        placeholder: false,
        url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843260/coachzone/IZ_ddbxhv.png',
        secure_url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843260/coachzone/IZ_ddbxhv.png',
        original_filename: 'file',
      },
    },
    // createdBy: null,
    // updatedBy: null,
    // updatedAt_utc: '2020-12-19T21:35:35.739Z',
    // updatedAt_offset: '+00:00',
    // createdAt_utc: '2020-12-19T21:35:35.739Z',
    // createdAt_offset: '+00:00',
  },
  {
    name: 'RB course z pilka',
    description: ' juke -> juke -> przekok obunóż -> truck tarczy ',
    position: 'RB',
    photo: {
      id: '5dfbed262849d7961377c2c0',
      filename: 'rbcourse.png',
      originalFilename: 'rbcourse.png',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'coach-zone-keystone/5e2a1413689b2835ae71d1a9',
        width: 750,
        height: 457,
        format: 'png',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 27871,
        type: 'upload',
        etag: 'e1fdf84d5126b6ca2e1c8ef9532be5a5',
        placeholder: false,
        url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843260/coachzone/RBcourse_inkmkz.png',
        secure_url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843260/coachzone/RBcourse_inkmkz.png',
        original_filename: 'file',
      },
    },
    // createdBy: null,
    // updatedBy: null,
    // updatedAt_utc: '2020-12-19T21:35:35.739Z',
    // updatedAt_offset: '+00:00',
    // createdAt_utc: '2020-12-19T21:35:35.739Z',
    // createdAt_offset: '+00:00',
  },
  {
    name: 'Zone drop',
    description: 'zawodnik ustawia się w pozycji. Za nim, w odległości 10y od siebie staje 2 WR. Na sygnał zawodnik robi drop do strefy pomiędzy 2 WRów. QB obraca się z piłką patrząc na jednego lub drugiego WR, zawodnik reaguje side stepami w tą stronę. Następnie QB rzuca piłkę, a zawodnik stara się zbić podanie',
    position: 'DB',
    photo: {
      id: '5dfbed262849d7961377c2c0',
      filename: 'zonedrop.png',
      originalFilename: 'zonedrop.png',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'coach-zone-keystone/5e2a142c689b2835ae71d1ab',
        width: 750,
        height: 457,
        format: 'png',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 27871,
        type: 'upload',
        etag: 'e1fdf84d5126b6ca2e1c8ef9532be5a5',
        placeholder: false,
        url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843260/coachzone/Zonedrop_ggvzoo.png',
        secure_url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843260/coachzone/Zonedrop_ggvzoo.png',
        original_filename: 'file',
      },
    },
    // createdBy: null,
    // updatedBy: null,
    // updatedAt_utc: '2020-12-19T21:35:35.739Z',
    // updatedAt_offset: '+00:00',
    // createdAt_utc: '2020-12-19T21:35:35.739Z',
    // createdAt_offset: '+00:00',
  },
  {
    name: 'Zone cover',
    description: '2 DB ustawia się w strefach. 2WR przebiega w poprzek stref, zaczynając z przeciwległych ston. DB kryją Wrów poruszając się w obrębie swoich stref.  QB rzuca w dowolnym momencie do jednego z WR',
    position: 'DB',
    photo: {
      id: '5dfbed262849d7961377c2c0',
      filename: 'zonecover.png',
      originalFilename: 'zonecover.png',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'coach-zone-keystone/5e2a143f689b2835ae71d1ad',
        width: 750,
        height: 457,
        format: 'png',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 27871,
        type: 'upload',
        etag: 'e1fdf84d5126b6ca2e1c8ef9532be5a5',
        placeholder: false,
        url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843260/coachzone/zonecover_vqherp.png',
        secure_url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843260/coachzone/zonecover_vqherp.png',
        original_filename: 'file',
      },
    },
    // createdBy: null,
    // updatedBy: null,
    // updatedAt_utc: '2020-12-19T21:35:35.739Z',
    // updatedAt_offset: '+00:00',
    // createdAt_utc: '2020-12-19T21:35:35.739Z',
    // createdAt_offset: '+00:00',
  },
  {
    name: 'Angle tackle',
    description: 'zawodnik ustawia się naprzeciw blokującego. 5y za plecami blokującego ustawia się RB. Na sygnał Zawodnik wchodzi w kontakt z blokującym przeciwnikiem i obserwuje RB. RB rusza po skosie w wybraną przez siebie stronę. Zawodnik zrzuca blok i tackluje biegacza',
    position: 'LB',
    photo: {
      id: '5dfbed262849d7961377c2c0',
      filename: 'angletackle.png',
      originalFilename: 'angletackle.png',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'coach-zone-keystone/5e2a145d689b2835ae71d1af',
        width: 750,
        height: 457,
        format: 'png',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 27871,
        type: 'upload',
        etag: 'e1fdf84d5126b6ca2e1c8ef9532be5a5',
        placeholder: false,
        url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843260/coachzone/Angletackle_kqwfjq.png',
        secure_url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843260/coachzone/Angletackle_kqwfjq.png',
        original_filename: 'file',
      },
    },
    // createdBy: null,
    // updatedBy: null,
    // updatedAt_utc: '2020-12-19T21:35:35.739Z',
    // updatedAt_offset: '+00:00',
    // createdAt_utc: '2020-12-19T21:35:35.739Z',
    // createdAt_offset: '+00:00',
  },
  {
    name: '1 on 1 run block',
    description: 'razem z DL i TE! Ustawiamy kwadrat 4x4y. OL startuje na skraju kwadratum DL ustawia się na jego ramieniu od wnętrza kwadratu. Na sygnał DL rushuje a OL robi run block. DL stara się przejść na drugą stronę kwadratu',
    position: 'DL',
    photo: {
      id: '5dfbed262849d7961377c2c0',
      filename: '1v1ol.png',
      originalFilename: '1v1ol.png',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'coach-zone-keystone/5e2a147b689b2835ae71d1b1',
        width: 750,
        height: 457,
        format: 'png',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 27871,
        type: 'upload',
        etag: 'e1fdf84d5126b6ca2e1c8ef9532be5a5',
        placeholder: false,
        url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843094/coachzone/conditioningOL_xfpf7h.png',
        secure_url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843094/coachzone/conditioningOL_xfpf7h.png',
        original_filename: 'file',
      },
    },
    // createdBy: null,
    // updatedBy: null,
    // updatedAt_utc: '2020-12-19T21:35:35.739Z',
    // updatedAt_offset: '+00:00',
    // createdAt_utc: '2020-12-19T21:35:35.739Z',
    // createdAt_offset: '+00:00',
  },
  {
    name: 'Goal line tackle',
    description: 'D# i O# ustawiająsię naprzeciw siebie w odległości 2y. Przed O# na położonej tarczy leży piłka. Na sygnał O# łapie piłkę i biegnie po prawej lub lewej stronie tarczy, próbując przebiec goal line (mieszcząc się pomiędzy znacznikami). D# tackluje go',
    position: 'WR',
    photo: {
      id: '5dfbed262849d7961377c2c0',
      filename: '1v1wr.png',
      originalFilename: '1v1wr.png',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'coach-zone-keystone/5e2a149b689b2835ae71d1b3',
        width: 750,
        height: 457,
        format: 'png',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 27871,
        type: 'upload',
        etag: 'e1fdf84d5126b6ca2e1c8ef9532be5a5',
        placeholder: false,
        url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843261/coachzone/1v1wr_anmhaw.png',
        secure_url:
          'https://res.cloudinary.com/dzhuwnmtp/image/upload/v1667843261/coachzone/1v1wr_anmhaw.png',
        original_filename: 'file',
      },
    },
    // createdBy: null,
    // updatedBy: null,
    // updatedAt_utc: '2020-12-19T21:35:35.739Z',
    // updatedAt_offset: '+00:00',
    // createdAt_utc: '2020-12-19T21:35:35.739Z',
    // createdAt_offset: '+00:00',
  },
];
